package view;

import dao.ClienteDaoImpl;
import java.util.ArrayList;
import java.util.List;
import javax.swing.JOptionPane;
import javax.swing.table.DefaultTableModel;
import model.Cliente;

public class FormCliente extends javax.swing.JInternalFrame {

    ClienteDaoImpl clientImpl = new ClienteDaoImpl();
    public boolean isEditing = false;
    public static List<Cliente> listaCliente;

    public FormCliente() {
        initComponents();
        listaCliente = new ArrayList<>();
        tblCliente();
        inicilize();
    }

    public void tblCliente() {
        listaCliente = clientImpl.getAllClientes();
        if (listaCliente != null && !listaCliente.isEmpty()) {

            DefaultTableModel modeloCli = new DefaultTableModel(new Object[]{"Código",
                "Nome",
                "Fone",
                "Email",
                "Endereço"}, 0);

            for (int i = 0; i < listaCliente.size(); i++) {
                Object linhaCli[] = new Object[]{listaCliente.get(i).getCodigo(),
                    listaCliente.get(i).getNome(),
                    listaCliente.get(i).getFone(),
                    listaCliente.get(i).getEmail(),
                    listaCliente.get(i).getEndereco()};
                modeloCli.addRow(linhaCli);
            }

            jTbCli.setModel(modeloCli);
            jTbCli.getColumnModel().getColumn(0).setPreferredWidth(50);
            jTbCli.getColumnModel().getColumn(1).setPreferredWidth(250);
            jTbCli.getColumnModel().getColumn(2).setPreferredWidth(80);
            jTbCli.getColumnModel().getColumn(3).setPreferredWidth(80);
            jTbCli.getColumnModel().getColumn(4).setPreferredWidth(80);

            jTbCli.setModel(modeloCli);
        } else {
            JOptionPane.showMessageDialog(null, "Ainda não há registros de clientes cadastrados");
        }

    }

    public void enableButtons(boolean choose) {
        btnNewCli.setEnabled(choose);
        btnCanCli.setEnabled(choose);
        btnEditCli.setEnabled(choose);
        btnExcCli.setEnabled(choose);
        btnSaveCli.setEnabled(choose);
    }

    public void enableInputs(boolean choose) {
        jTfCodCli.setEnabled(false);
        jTfNameCli.setEnabled(choose);
        jTfFoneCli.setEnabled(choose);
        jTfMailCli.setEnabled(choose);
        jTaCli.setEnabled(choose);

        if (!choose) {
            jTfNameCli.setText("");
            jTfCodCli.setText("");
            jTfFoneCli.setText("");
            jTfMailCli.setText("");
            jTaCli.setText("");  // Para o campo de texto de endereço, supondo que seja uma JTextArea
        }

    }

    public void inicilize() {

        enableButtons(false);
        enableInputs(false);
        btnNewCli.setEnabled(true);
        isEditing = false;
    }

    /**
     * This method is called from within the constructor to initialize the form.
     * WARNING: Do NOT modify this code. The content of this method is always
     * regenerated by the Form Editor.
     */
    @SuppressWarnings("unchecked")
    // <editor-fold defaultstate="collapsed" desc="Generated Code">//GEN-BEGIN:initComponents
    private void initComponents() {

        jLabel1 = new javax.swing.JLabel();
        jTfCodCli = new javax.swing.JTextField();
        jLabel2 = new javax.swing.JLabel();
        jTfNameCli = new javax.swing.JTextField();
        jLabel3 = new javax.swing.JLabel();
        jTfFoneCli = new javax.swing.JTextField();
        jLabel4 = new javax.swing.JLabel();
        jTfMailCli = new javax.swing.JTextField();
        jLabel5 = new javax.swing.JLabel();
        jScrollPane1 = new javax.swing.JScrollPane();
        jTbCli = new javax.swing.JTable();
        btnNewCli = new javax.swing.JButton();
        btnEditCli = new javax.swing.JButton();
        btnExcCli = new javax.swing.JButton();
        btnCanCli = new javax.swing.JButton();
        btnSaveCli = new javax.swing.JButton();
        jScrollPane2 = new javax.swing.JScrollPane();
        jTaCli = new javax.swing.JTextArea();

        setClosable(true);
        setIconifiable(true);
        setTitle("Cadastro Cliente");

        jLabel1.setText("Código:");

        jTfCodCli.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                jTfCodCliActionPerformed(evt);
            }
        });

        jLabel2.setText("Nome:");

        jTfNameCli.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                jTfNameCliActionPerformed(evt);
            }
        });

        jLabel3.setText("Fone:");

        jTfFoneCli.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                jTfFoneCliActionPerformed(evt);
            }
        });

        jLabel4.setText("Email:");

        jTfMailCli.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                jTfMailCliActionPerformed(evt);
            }
        });

        jLabel5.setText("Endereço:");

        jTbCli.setModel(new javax.swing.table.DefaultTableModel(
            new Object [][] {

            },
            new String [] {
                "Código", "Nome", "Fone", "Email", "Endereço"
            }
        ));
        jTbCli.addMouseListener(new java.awt.event.MouseAdapter() {
            public void mouseClicked(java.awt.event.MouseEvent evt) {
                jTbCliMouseClicked(evt);
            }
        });
        jScrollPane1.setViewportView(jTbCli);

        btnNewCli.setText("Novo");
        btnNewCli.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                btnNewCliActionPerformed(evt);
            }
        });

        btnEditCli.setText("Editar");
        btnEditCli.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                btnEditCliActionPerformed(evt);
            }
        });

        btnExcCli.setText("Excluir");
        btnExcCli.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                btnExcCliActionPerformed(evt);
            }
        });

        btnCanCli.setText("Cancelar");
        btnCanCli.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                btnCanCliActionPerformed(evt);
            }
        });

        btnSaveCli.setText("Salvar");
        btnSaveCli.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                btnSaveCliActionPerformed(evt);
            }
        });

        jTaCli.setColumns(20);
        jTaCli.setRows(5);
        jScrollPane2.setViewportView(jTaCli);

        javax.swing.GroupLayout layout = new javax.swing.GroupLayout(getContentPane());
        getContentPane().setLayout(layout);
        layout.setHorizontalGroup(
            layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(javax.swing.GroupLayout.Alignment.TRAILING, layout.createSequentialGroup()
                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addGroup(layout.createSequentialGroup()
                        .addGap(59, 59, 59)
                        .addComponent(btnNewCli)
                        .addGap(77, 77, 77)
                        .addComponent(btnEditCli))
                    .addGroup(layout.createSequentialGroup()
                        .addGap(24, 24, 24)
                        .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                            .addComponent(jScrollPane2, javax.swing.GroupLayout.PREFERRED_SIZE, 300, javax.swing.GroupLayout.PREFERRED_SIZE)
                            .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING, false)
                                .addComponent(jLabel1)
                                .addComponent(jLabel2)
                                .addComponent(jLabel3)
                                .addComponent(jLabel4)
                                .addComponent(jLabel5)
                                .addComponent(jTfMailCli, javax.swing.GroupLayout.DEFAULT_SIZE, 300, Short.MAX_VALUE)
                                .addComponent(jTfFoneCli)
                                .addComponent(jTfNameCli)
                                .addComponent(jTfCodCli)))))
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED, 33, Short.MAX_VALUE)
                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addGroup(layout.createSequentialGroup()
                        .addComponent(btnExcCli)
                        .addGap(58, 58, 58)
                        .addComponent(btnCanCli)
                        .addGap(49, 49, 49)
                        .addComponent(btnSaveCli))
                    .addComponent(jScrollPane1, javax.swing.GroupLayout.PREFERRED_SIZE, 350, javax.swing.GroupLayout.PREFERRED_SIZE))
                .addContainerGap(31, Short.MAX_VALUE))
        );
        layout.setVerticalGroup(
            layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(layout.createSequentialGroup()
                .addGap(17, 17, 17)
                .addComponent(jLabel1)
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addGroup(layout.createSequentialGroup()
                        .addComponent(jTfCodCli, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                        .addGap(18, 18, 18)
                        .addComponent(jLabel2)
                        .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                        .addComponent(jTfNameCli, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                        .addGap(22, 22, 22)
                        .addComponent(jLabel3)
                        .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                        .addComponent(jTfFoneCli, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                        .addGap(18, 18, 18)
                        .addComponent(jLabel4)
                        .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                        .addComponent(jTfMailCli, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                        .addGap(18, 18, 18)
                        .addComponent(jLabel5)
                        .addGap(10, 10, 10)
                        .addComponent(jScrollPane2, javax.swing.GroupLayout.PREFERRED_SIZE, 160, javax.swing.GroupLayout.PREFERRED_SIZE))
                    .addComponent(jScrollPane1, javax.swing.GroupLayout.PREFERRED_SIZE, 416, javax.swing.GroupLayout.PREFERRED_SIZE))
                .addGap(18, 18, 18)
                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addComponent(btnNewCli)
                    .addComponent(btnEditCli)
                    .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                        .addComponent(btnExcCli)
                        .addComponent(btnCanCli)
                        .addComponent(btnSaveCli)))
                .addContainerGap(19, Short.MAX_VALUE))
        );

        pack();
    }// </editor-fold>//GEN-END:initComponents

    private void jTfCodCliActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_jTfCodCliActionPerformed
        // TODO add your handling code here:
    }//GEN-LAST:event_jTfCodCliActionPerformed

    private void jTfNameCliActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_jTfNameCliActionPerformed
        // TODO add your handling code here:
    }//GEN-LAST:event_jTfNameCliActionPerformed

    private void jTfFoneCliActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_jTfFoneCliActionPerformed
        // TODO add your handling code here:
    }//GEN-LAST:event_jTfFoneCliActionPerformed

    private void jTfMailCliActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_jTfMailCliActionPerformed
        // TODO add your handling code here:
    }//GEN-LAST:event_jTfMailCliActionPerformed

    private void btnExcCliActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_btnExcCliActionPerformed
        int linhaSelecionada = jTbCli.getSelectedRow();
        if (linhaSelecionada != -1) {
            int a = JOptionPane.showConfirmDialog(null, "Realmente deseja excluir?", "Confirmar", JOptionPane.YES_OPTION);

            if (a == JOptionPane.YES_OPTION) {

                int codigo = Integer.parseInt(jTbCli.getValueAt(linhaSelecionada, 0).toString());

                clientImpl.deleteCliente(codigo);
                
                enableButtons(false);
                btnNewCli.setEnabled(true);
                enableInputs(false);
            }
        } else {
            JOptionPane.showMessageDialog(null, "Selecione um cliente para excluir.");
        }

        tblCliente();
    }//GEN-LAST:event_btnExcCliActionPerformed

    private void btnNewCliActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_btnNewCliActionPerformed
        btnSaveCli.setEnabled(true);
        btnNewCli.setEnabled(false);
        btnCanCli.setEnabled(true);
        enableInputs(true);
    }//GEN-LAST:event_btnNewCliActionPerformed

    private void btnEditCliActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_btnEditCliActionPerformed

        if (jTbCli.getSelectedRow() == -1) {
            JOptionPane.showMessageDialog(null, "Selecione um cliente para editar.");
            return;
        } else {

            enableButtons(false);
            btnSaveCli.setEnabled(true);
            btnCanCli.setEnabled(true);
            btnEditCli.setEnabled(false);
            enableInputs(true);
            isEditing = true;
    }//GEN-LAST:event_btnEditCliActionPerformed
    }
    private void btnCanCliActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_btnCanCliActionPerformed
        enableButtons(false);
        btnNewCli.setEnabled(true);
        enableInputs(false);
        isEditing = false;
    }//GEN-LAST:event_btnCanCliActionPerformed

    private void btnSaveCliActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_btnSaveCliActionPerformed

        String nome = jTfNameCli.getText();
        String telefone = jTfFoneCli.getText();
        String email = jTfMailCli.getText();
        String endereco = jTaCli.getText();

        int a = JOptionPane.showConfirmDialog(null, "Deseja Realmente salvar essas informações?\n\n"
                + "\nNome: " + nome
                + "\nTelefone: " + telefone
                + "\nEmail: " + email
                + "\nEndereço: " + endereco,
                "Confirmar", JOptionPane.YES_OPTION);

        if (a == JOptionPane.YES_OPTION && (!nome.isEmpty() && !telefone.isEmpty() && !email.isEmpty() && !endereco.isEmpty())) {

            if (isEditing) {
                int codigo = Integer.parseInt(jTfCodCli.getText());
                Cliente cliente = new Cliente(codigo, nome, telefone, email, endereco);
                clientImpl.updateCliente(cliente);

            } else {
                Cliente cliente = new Cliente(nome, telefone, email, endereco);
                clientImpl.addCliente(cliente);
            }
            inicilize();
            tblCliente();
        } else if ((nome.isEmpty() || telefone.isEmpty() || email.isEmpty() || endereco.isEmpty())) {
            JOptionPane.showMessageDialog(null, "Por favor preencha todos os campos");
        }
    }//GEN-LAST:event_btnSaveCliActionPerformed

    private void jTbCliMouseClicked(java.awt.event.MouseEvent evt) {//GEN-FIRST:event_jTbCliMouseClicked
        btnExcCli.setEnabled(true);
        btnCanCli.setEnabled(true);
        btnNewCli.setEnabled(false);
        btnSaveCli.setEnabled(false);
        btnEditCli.setEnabled(true);
        enableInputs(false);

        int linhaSelecionada = jTbCli.getSelectedRow();

        jTfCodCli.setText(jTbCli.getValueAt(linhaSelecionada, 0).toString());
        jTfNameCli.setText(jTbCli.getValueAt(linhaSelecionada, 1).toString());
        jTfFoneCli.setText(jTbCli.getValueAt(linhaSelecionada, 2).toString());
        jTfMailCli.setText(jTbCli.getValueAt(linhaSelecionada, 3).toString());
        jTaCli.setText(jTbCli.getValueAt(linhaSelecionada, 4).toString());
    }//GEN-LAST:event_jTbCliMouseClicked


    // Variables declaration - do not modify//GEN-BEGIN:variables
    private javax.swing.JButton btnCanCli;
    private javax.swing.JButton btnEditCli;
    private javax.swing.JButton btnExcCli;
    private javax.swing.JButton btnNewCli;
    private javax.swing.JButton btnSaveCli;
    private javax.swing.JLabel jLabel1;
    private javax.swing.JLabel jLabel2;
    private javax.swing.JLabel jLabel3;
    private javax.swing.JLabel jLabel4;
    private javax.swing.JLabel jLabel5;
    private javax.swing.JScrollPane jScrollPane1;
    private javax.swing.JScrollPane jScrollPane2;
    private javax.swing.JTextArea jTaCli;
    private javax.swing.JTable jTbCli;
    private javax.swing.JTextField jTfCodCli;
    private javax.swing.JTextField jTfFoneCli;
    private javax.swing.JTextField jTfMailCli;
    private javax.swing.JTextField jTfNameCli;
    // End of variables declaration//GEN-END:variables
}
