/*
 * Click nbfs://nbhost/SystemFileSystem/Templates/Licenses/license-default.txt to change this license
 * Click nbfs://nbhost/SystemFileSystem/Templates/GUIForms/JInternalFrame.java to edit this template
 */
package view;

import model.Fornecedor;
import dao.FornecedorDaoImpl;
import java.util.List;
import javax.swing.JOptionPane;
import javax.swing.table.DefaultTableModel;

public class FormFornecedor extends javax.swing.JInternalFrame {

    FornecedorDaoImpl fornecedorImpl = new FornecedorDaoImpl();
    public boolean isEditing = false;
    public static List<Fornecedor> listaFornecedor;

    public void tblFornecedor() {
        listaFornecedor = fornecedorImpl.getAllFornecedores();
        DefaultTableModel modeloFor = new DefaultTableModel(new Object[]{"Código",
            "Contato",
            "E-mail",
            "Telefone",
            "Empresa"}, 0);

        for (int i = 0; i < listaFornecedor.size(); i++) {
            Object linhaFor[] = new Object[]{
                listaFornecedor.get(i).getCod(),
                listaFornecedor.get(i).getContato(),
                listaFornecedor.get(i).getContato(),
                listaFornecedor.get(i).getFone(),
                listaFornecedor.get(i).getEmpresa()
            };
            modeloFor.addRow(linhaFor);
        }
        jTbFor.setModel(modeloFor);
        jTbFor.getColumnModel().getColumn(0).setPreferredWidth(100);
        jTbFor.getColumnModel().getColumn(1).setPreferredWidth(150);
        jTbFor.getColumnModel().getColumn(2).setPreferredWidth(100);
        jTbFor.getColumnModel().getColumn(3).setPreferredWidth(100);
        jTbFor.getColumnModel().getColumn(4).setPreferredWidth(100);

    }

    public FormFornecedor() {
        initComponents();
        tblFornecedor();
        inicilize();
    }

    public void enableButtons(boolean choose) {
        btnNewFor.setEnabled(choose);
        btnCanFor.setEnabled(choose);
        btnEditFor.setEnabled(choose);
        btnExcFor.setEnabled(choose);
        btnSaveFor.setEnabled(choose);
    }
    
    public void enableInputs(boolean choose) {
        jTfCodFor.setEnabled(false);
        jTfEmpFor.setEnabled(choose);
        jTfContFor.setEnabled(choose);
        jTfFoneFor.setEnabled(choose);
        jTfMailFor.setEnabled(choose);

        
        

        if (!choose) {
            jTfCodFor.setText("");
            jTfEmpFor.setText("");
            jTfContFor.setText("");
            jTfFoneFor.setText("");
            jTfMailFor.setText("");

        }
        
    }
    
    public void inicilize() {
        enableButtons(false);
        enableInputs(false);
        btnNewFor.setEnabled(true);
        isEditing = false;
    }
    
    /**
     * This method is called from within the constructor to initialize the form.
     * WARNING: Do NOT modify this code. The content of this method is always
     * regenerated by the Form Editor.
     */
    @SuppressWarnings("unchecked")
    // <editor-fold defaultstate="collapsed" desc="Generated Code">//GEN-BEGIN:initComponents
    private void initComponents() {

        jLabel1 = new javax.swing.JLabel();
        jTfCodFor = new javax.swing.JTextField();
        jLabel2 = new javax.swing.JLabel();
        jTfContFor = new javax.swing.JTextField();
        jLabel3 = new javax.swing.JLabel();
        jTfMailFor = new javax.swing.JTextField();
        jLabel4 = new javax.swing.JLabel();
        jTfFoneFor = new javax.swing.JTextField();
        jLabel5 = new javax.swing.JLabel();
        jScrollPane1 = new javax.swing.JScrollPane();
        jTbFor = new javax.swing.JTable();
        btnNewFor = new javax.swing.JButton();
        btnEditFor = new javax.swing.JButton();
        btnExcFor = new javax.swing.JButton();
        btnCanFor = new javax.swing.JButton();
        btnSaveFor = new javax.swing.JButton();
        jScrollPane2 = new javax.swing.JScrollPane();
        jTfEmpFor = new javax.swing.JTextArea();

        setClosable(true);
        setIconifiable(true);
        setTitle("Cadastro Fornecedor");

        jLabel1.setText("Código:");

        jTfCodFor.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                jTfCodForActionPerformed(evt);
            }
        });

        jLabel2.setText("Contato:");

        jTfContFor.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                jTfContForActionPerformed(evt);
            }
        });

        jLabel3.setText("Email:");

        jTfMailFor.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                jTfMailForActionPerformed(evt);
            }
        });

        jLabel4.setText("Fone:");

        jTfFoneFor.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                jTfFoneForActionPerformed(evt);
            }
        });

        jLabel5.setText("Empresa:");

        jTbFor.setModel(new javax.swing.table.DefaultTableModel(
            new Object [][] {

            },
            new String [] {
                "Código", "Contato", "E-mail", "Telefone", "Empresa"
            }
        ));
        jTbFor.addMouseListener(new java.awt.event.MouseAdapter() {
            public void mouseClicked(java.awt.event.MouseEvent evt) {
                jTbForMouseClicked(evt);
            }
        });
        jScrollPane1.setViewportView(jTbFor);

        btnNewFor.setText("Novo");
        btnNewFor.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                btnNewForActionPerformed(evt);
            }
        });

        btnEditFor.setText("Editar");
        btnEditFor.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                btnEditForActionPerformed(evt);
            }
        });

        btnExcFor.setText("Excluir");
        btnExcFor.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                btnExcForActionPerformed(evt);
            }
        });

        btnCanFor.setText("Cancelar");
        btnCanFor.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                btnCanForActionPerformed(evt);
            }
        });

        btnSaveFor.setText("Salvar");
        btnSaveFor.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                btnSaveForActionPerformed(evt);
            }
        });

        jTfEmpFor.setColumns(20);
        jTfEmpFor.setRows(5);
        jScrollPane2.setViewportView(jTfEmpFor);

        javax.swing.GroupLayout layout = new javax.swing.GroupLayout(getContentPane());
        getContentPane().setLayout(layout);
        layout.setHorizontalGroup(
            layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(javax.swing.GroupLayout.Alignment.TRAILING, layout.createSequentialGroup()
                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addGroup(layout.createSequentialGroup()
                        .addGap(59, 59, 59)
                        .addComponent(btnNewFor)
                        .addGap(77, 77, 77)
                        .addComponent(btnEditFor))
                    .addGroup(layout.createSequentialGroup()
                        .addGap(24, 24, 24)
                        .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                            .addComponent(jScrollPane2, javax.swing.GroupLayout.PREFERRED_SIZE, 300, javax.swing.GroupLayout.PREFERRED_SIZE)
                            .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING, false)
                                .addComponent(jLabel1)
                                .addComponent(jLabel2)
                                .addComponent(jLabel3)
                                .addComponent(jLabel4)
                                .addComponent(jLabel5)
                                .addComponent(jTfFoneFor, javax.swing.GroupLayout.DEFAULT_SIZE, 300, Short.MAX_VALUE)
                                .addComponent(jTfMailFor)
                                .addComponent(jTfContFor)
                                .addComponent(jTfCodFor)))))
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.UNRELATED)
                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addGroup(layout.createSequentialGroup()
                        .addGap(0, 21, Short.MAX_VALUE)
                        .addComponent(btnExcFor)
                        .addGap(58, 58, 58)
                        .addComponent(btnCanFor)
                        .addGap(49, 49, 49)
                        .addComponent(btnSaveFor)
                        .addGap(0, 48, Short.MAX_VALUE))
                    .addComponent(jScrollPane1, javax.swing.GroupLayout.PREFERRED_SIZE, 0, Short.MAX_VALUE))
                .addContainerGap())
        );
        layout.setVerticalGroup(
            layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(layout.createSequentialGroup()
                .addGap(17, 17, 17)
                .addComponent(jLabel1)
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING, false)
                    .addGroup(layout.createSequentialGroup()
                        .addComponent(jTfCodFor, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                        .addGap(18, 18, 18)
                        .addComponent(jLabel2)
                        .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                        .addComponent(jTfContFor, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                        .addGap(22, 22, 22)
                        .addComponent(jLabel3)
                        .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                        .addComponent(jTfMailFor, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                        .addGap(18, 18, 18)
                        .addComponent(jLabel4)
                        .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                        .addComponent(jTfFoneFor, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                        .addGap(18, 18, 18)
                        .addComponent(jLabel5)
                        .addGap(18, 18, 18)
                        .addComponent(jScrollPane2))
                    .addComponent(jScrollPane1, javax.swing.GroupLayout.PREFERRED_SIZE, 416, javax.swing.GroupLayout.PREFERRED_SIZE))
                .addGap(18, 18, 18)
                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addComponent(btnNewFor)
                    .addComponent(btnEditFor)
                    .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                        .addComponent(btnExcFor)
                        .addComponent(btnCanFor)
                        .addComponent(btnSaveFor)))
                .addContainerGap(19, Short.MAX_VALUE))
        );

        pack();
    }// </editor-fold>//GEN-END:initComponents

    private void jTfCodForActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_jTfCodForActionPerformed
        // TODO add your handling code here:
    }//GEN-LAST:event_jTfCodForActionPerformed

    private void jTfContForActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_jTfContForActionPerformed
        // TODO add your handling code here:
    }//GEN-LAST:event_jTfContForActionPerformed

    private void jTfMailForActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_jTfMailForActionPerformed
        // TODO add your handling code here:
    }//GEN-LAST:event_jTfMailForActionPerformed

    private void jTfFoneForActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_jTfFoneForActionPerformed
        // TODO add your handling code here:
    }//GEN-LAST:event_jTfFoneForActionPerformed

    private void btnExcForActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_btnExcForActionPerformed
        int linhaSelecionada = jTbFor.getSelectedRow();
        if (linhaSelecionada != -1) {
            int a = JOptionPane.showConfirmDialog(null, "Realmente deseja excluir?", "Confirmar", JOptionPane.YES_OPTION);

            if (a == JOptionPane.YES_OPTION) {

                int codigo = Integer.parseInt(jTbFor.getValueAt(linhaSelecionada, 0).toString());

                fornecedorImpl.deleteFornecedor(codigo);
                
                enableButtons(false);
                btnNewFor.setEnabled(true);
                enableInputs(false);
            }
        } else {
            JOptionPane.showMessageDialog(null, "Selecione um cliente para excluir.");
        }

        tblFornecedor();
        inicilize();
    }//GEN-LAST:event_btnExcForActionPerformed

    private void btnNewForActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_btnNewForActionPerformed
        enableButtons(false);
        enableInputs(true);
        btnCanFor.setEnabled(true);
        btnSaveFor.setEnabled(true);
        
        isEditing = false;
    }//GEN-LAST:event_btnNewForActionPerformed

    private void btnEditForActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_btnEditForActionPerformed
        enableInputs(true);
        btnCanFor.setEnabled(true);
        btnEditFor.setEnabled(false);
        btnSaveFor.setEnabled(true);
        btnExcFor.setEnabled(false);
        isEditing = true;
    }//GEN-LAST:event_btnEditForActionPerformed

    private void btnCanForActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_btnCanForActionPerformed
        enableButtons(false);
        btnNewFor.setEnabled(true);
        enableInputs(false);
        isEditing = false;
    }//GEN-LAST:event_btnCanForActionPerformed

    private void btnSaveForActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_btnSaveForActionPerformed
        
        String empresa = jTfEmpFor.getText();
        String contato = jTfContFor.getText();
        String fone = jTfFoneFor.getText();
        String email = jTfMailFor.getText();

        int a = JOptionPane.showConfirmDialog(null, "Deseja realmente salvar essas informações?\n\n"
                + "\nEmpresa: " + empresa
                + "\nContato: " + contato
                + "\nFone: " + fone
                + "\nEmail: " + email,
                "Confirmar", JOptionPane.YES_OPTION);

        if (a == JOptionPane.YES_OPTION && (!empresa.isEmpty() && !contato.isEmpty() && !fone.isEmpty() && !email.isEmpty())) {

            if (isEditing) {
                int cod = Integer.parseInt(jTfCodFor.getText());
                Fornecedor fornecedor = new Fornecedor(cod, empresa, contato, fone, email);
                fornecedorImpl.updateFornecedor(fornecedor);
                isEditing = false;
            } else {
                Fornecedor fornecedor = new Fornecedor(empresa, contato, fone, email);
                fornecedorImpl.addFornecedor(fornecedor);
            }
            
            inicilize();
            tblFornecedor();
           
        } else if ((empresa.isEmpty() || contato.isEmpty() || fone.isEmpty() || email.isEmpty())) {
            JOptionPane.showMessageDialog(null, "Por favor preencha todos os campos");
        }
    }//GEN-LAST:event_btnSaveForActionPerformed

    private void jTbForMouseClicked(java.awt.event.MouseEvent evt) {//GEN-FIRST:event_jTbForMouseClicked
        int linhaSelecionada = jTbFor.getSelectedRow();
        inicilize();
        jTfCodFor.setText(jTbFor.getValueAt(linhaSelecionada, 0).toString());
        jTfEmpFor.setText(jTbFor.getValueAt(linhaSelecionada, 4).toString());
        jTfContFor.setText(jTbFor.getValueAt(linhaSelecionada, 1).toString());
        jTfFoneFor.setText(jTbFor.getValueAt(linhaSelecionada, 3).toString());
        jTfMailFor.setText(jTbFor.getValueAt(linhaSelecionada, 2).toString());

        btnNewFor.setEnabled(false);
        btnEditFor.setEnabled(true);
        btnCanFor.setEnabled(true);
        btnExcFor.setEnabled(true);

    }//GEN-LAST:event_jTbForMouseClicked


    // Variables declaration - do not modify//GEN-BEGIN:variables
    private javax.swing.JButton btnCanFor;
    private javax.swing.JButton btnEditFor;
    private javax.swing.JButton btnExcFor;
    private javax.swing.JButton btnNewFor;
    private javax.swing.JButton btnSaveFor;
    private javax.swing.JLabel jLabel1;
    private javax.swing.JLabel jLabel2;
    private javax.swing.JLabel jLabel3;
    private javax.swing.JLabel jLabel4;
    private javax.swing.JLabel jLabel5;
    private javax.swing.JScrollPane jScrollPane1;
    private javax.swing.JScrollPane jScrollPane2;
    private javax.swing.JTable jTbFor;
    private javax.swing.JTextField jTfCodFor;
    private javax.swing.JTextField jTfContFor;
    private javax.swing.JTextArea jTfEmpFor;
    private javax.swing.JTextField jTfFoneFor;
    private javax.swing.JTextField jTfMailFor;
    // End of variables declaration//GEN-END:variables
}
