/*
 * Click nbfs://nbhost/SystemFileSystem/Templates/Licenses/license-default.txt to change this license
 * Click nbfs://nbhost/SystemFileSystem/Templates/GUIForms/JInternalFrame.java to edit this template
 */
package view;

/**
 *
 * @author william_c_pereira
 */
public class FormCliente extends javax.swing.JInternalFrame {

    /**
     * Creates new form FormCliente
     */
    public FormCliente() {
        initComponents();
    }

    /**
     * This method is called from within the constructor to initialize the form.
     * WARNING: Do NOT modify this code. The content of this method is always
     * regenerated by the Form Editor.
     */
    @SuppressWarnings("unchecked")
    // <editor-fold defaultstate="collapsed" desc="Generated Code">//GEN-BEGIN:initComponents
    private void initComponents() {

        jLabel1 = new javax.swing.JLabel();
        jTfCodCli = new javax.swing.JTextField();
        jLabel2 = new javax.swing.JLabel();
        jTfNameCli = new javax.swing.JTextField();
        jLabel3 = new javax.swing.JLabel();
        jTfFoneCli = new javax.swing.JTextField();
        jLabel4 = new javax.swing.JLabel();
        jTfMailCli = new javax.swing.JTextField();
        jLabel5 = new javax.swing.JLabel();
        jTfEndCli = new javax.swing.JTextField();
        jScrollPane1 = new javax.swing.JScrollPane();
        jTbCli = new javax.swing.JTable();
        btnNewCli = new javax.swing.JButton();
        btnEditCli = new javax.swing.JButton();
        btnExcCli = new javax.swing.JButton();
        btnCanCli = new javax.swing.JButton();
        btnSaveCli = new javax.swing.JButton();

        setClosable(true);
        setIconifiable(true);
        setTitle("Cadastro Cliente");

        jLabel1.setText("Código:");

        jTfCodCli.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                jTfCodCliActionPerformed(evt);
            }
        });

        jLabel2.setText("Nome:");

        jTfNameCli.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                jTfNameCliActionPerformed(evt);
            }
        });

        jLabel3.setText("Fone:");

        jTfFoneCli.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                jTfFoneCliActionPerformed(evt);
            }
        });

        jLabel4.setText("Email:");

        jTfMailCli.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                jTfMailCliActionPerformed(evt);
            }
        });

        jLabel5.setText("Endereço:");

        jTbCli.setModel(new javax.swing.table.DefaultTableModel(
            new Object [][] {
                {null, null, null, null, null},
                {null, null, null, null, null},
                {null, null, null, null, null},
                {null, null, null, null, null}
            },
            new String [] {
                "Matrícula", "Nome", "Fone", "Email", "Endereço"
            }
        ));
        jScrollPane1.setViewportView(jTbCli);

        btnNewCli.setText("Novo");

        btnEditCli.setText("Editar");

        btnExcCli.setText("Excluir");
        btnExcCli.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                btnExcCliActionPerformed(evt);
            }
        });

        btnCanCli.setText("Cancelar");

        btnSaveCli.setText("Salvar");

        javax.swing.GroupLayout layout = new javax.swing.GroupLayout(getContentPane());
        getContentPane().setLayout(layout);
        layout.setHorizontalGroup(
            layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(javax.swing.GroupLayout.Alignment.TRAILING, layout.createSequentialGroup()
                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addGroup(layout.createSequentialGroup()
                        .addGap(24, 24, 24)
                        .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING, false)
                            .addComponent(jLabel1)
                            .addComponent(jLabel2)
                            .addComponent(jLabel3)
                            .addComponent(jLabel4)
                            .addComponent(jLabel5)
                            .addComponent(jTfEndCli, javax.swing.GroupLayout.DEFAULT_SIZE, 300, Short.MAX_VALUE)
                            .addComponent(jTfMailCli)
                            .addComponent(jTfFoneCli)
                            .addComponent(jTfNameCli)
                            .addComponent(jTfCodCli)))
                    .addGroup(layout.createSequentialGroup()
                        .addGap(59, 59, 59)
                        .addComponent(btnNewCli)
                        .addGap(77, 77, 77)
                        .addComponent(btnEditCli)))
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED, 33, Short.MAX_VALUE)
                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addGroup(layout.createSequentialGroup()
                        .addComponent(btnExcCli)
                        .addGap(58, 58, 58)
                        .addComponent(btnCanCli)
                        .addGap(49, 49, 49)
                        .addComponent(btnSaveCli))
                    .addComponent(jScrollPane1, javax.swing.GroupLayout.PREFERRED_SIZE, 350, javax.swing.GroupLayout.PREFERRED_SIZE))
                .addContainerGap(31, Short.MAX_VALUE))
        );
        layout.setVerticalGroup(
            layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(layout.createSequentialGroup()
                .addGap(17, 17, 17)
                .addComponent(jLabel1)
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING, false)
                    .addGroup(layout.createSequentialGroup()
                        .addComponent(jTfCodCli, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                        .addGap(18, 18, 18)
                        .addComponent(jLabel2)
                        .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                        .addComponent(jTfNameCli, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                        .addGap(22, 22, 22)
                        .addComponent(jLabel3)
                        .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                        .addComponent(jTfFoneCli, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                        .addGap(18, 18, 18)
                        .addComponent(jLabel4)
                        .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                        .addComponent(jTfMailCli, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                        .addGap(18, 18, 18)
                        .addComponent(jLabel5)
                        .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.UNRELATED)
                        .addComponent(jTfEndCli, javax.swing.GroupLayout.PREFERRED_SIZE, 158, javax.swing.GroupLayout.PREFERRED_SIZE))
                    .addComponent(jScrollPane1, javax.swing.GroupLayout.PREFERRED_SIZE, 0, Short.MAX_VALUE))
                .addGap(18, 18, 18)
                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addComponent(btnNewCli)
                    .addComponent(btnEditCli)
                    .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                        .addComponent(btnExcCli)
                        .addComponent(btnCanCli)
                        .addComponent(btnSaveCli)))
                .addContainerGap(19, Short.MAX_VALUE))
        );

        pack();
    }// </editor-fold>//GEN-END:initComponents

    private void jTfCodCliActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_jTfCodCliActionPerformed
        // TODO add your handling code here:
    }//GEN-LAST:event_jTfCodCliActionPerformed

    private void jTfNameCliActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_jTfNameCliActionPerformed
        // TODO add your handling code here:
    }//GEN-LAST:event_jTfNameCliActionPerformed

    private void jTfFoneCliActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_jTfFoneCliActionPerformed
        // TODO add your handling code here:
    }//GEN-LAST:event_jTfFoneCliActionPerformed

    private void jTfMailCliActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_jTfMailCliActionPerformed
        // TODO add your handling code here:
    }//GEN-LAST:event_jTfMailCliActionPerformed

    private void btnExcCliActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_btnExcCliActionPerformed
        // TODO add your handling code here:
    }//GEN-LAST:event_btnExcCliActionPerformed


    // Variables declaration - do not modify//GEN-BEGIN:variables
    private javax.swing.JButton btnCanCli;
    private javax.swing.JButton btnEditCli;
    private javax.swing.JButton btnExcCli;
    private javax.swing.JButton btnNewCli;
    private javax.swing.JButton btnSaveCli;
    private javax.swing.JLabel jLabel1;
    private javax.swing.JLabel jLabel2;
    private javax.swing.JLabel jLabel3;
    private javax.swing.JLabel jLabel4;
    private javax.swing.JLabel jLabel5;
    private javax.swing.JScrollPane jScrollPane1;
    private javax.swing.JTable jTbCli;
    private javax.swing.JTextField jTfCodCli;
    private javax.swing.JTextField jTfEndCli;
    private javax.swing.JTextField jTfFoneCli;
    private javax.swing.JTextField jTfMailCli;
    private javax.swing.JTextField jTfNameCli;
    // End of variables declaration//GEN-END:variables
}
